# Site settings
title: Leandro Falero (Leo)
description: Jekyll Theme Minimal Resume
baseurl: "/personal_card" # the subpath of your site, e.g. /blog
url: "https://github.com/anthropoleo/personal_card" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Leandro Falero (Leo)
user_description: I'm a Data Scientist from Uruguay, living on the Gold Coast, Australia. I have a passion for building solutions and tackling complex problems. My enthusiasm for data science drives me to leverage data to inform decisions and deepen our understanding of human behaviour. I am particularly interested in the applications of artificial intelligence and enjoy collaborating with AI technologies to develop innovative solutions.
user_title: Data Scientist
email: leandrofaleroo@gmail.com
# twitter_username: lorem_ipsum
instagram_username: none
facebook_username: none
linkedin_username: none
github_username:  none
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

